### ISSUE TITLE
Turn off unimportant warnings in logs

### ISSUE THREAD

**Issue by d3adwolf** [RocketModFix/RocketModFix#111]
Hi, in the logs are often glimpsed errors that do not really affect anything, I suggest that they can be sorted out in some way:
- Disable
- Fix

That's all that's available at the moment:
```sql
ERROR: Shader Nature/SpeedTree Billboard shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
```
```sql
WARNING: Shader Unsupported: 'Standard' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
```
```sql
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Computer_2/Alive"
```
```sql
Fallback handler could not load library /data/serverfiles/Unturned_Headless_Data/MonoBleedingEdge/x86_64/data-0x5b4ff35c7b20.so
Fallback handler could not load library /data/serverfiles/Unturned_Headless_Data/MonoBleedingEdge/x86_64/data-0x5b4ff37442d0.so
gpath.c:115: assertion 'filename != NULL' failed
```
```sql
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: wrong ELF class: ELFCLASS32
[S_API] SteamAPI_Init(): Loaded '/data/.steam/sdk64/steamclient.so' OK.  (First tried local 'steamclient.so')
CAppInfoCacheReadFromDiskThread took 7 milliseconds to initialize
Setting breakpad minidump AppID = 304930
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197960265728 [API loaded no]
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
```

**Comment by sunnamed434** [comment]
Hi, these logs are coming from Unturned/Unity itself not rocket, they can be hidden with "harmony patches" (but that would require additional not super important support for that in future, and also it might break at some point) + will include new library in the project.

I don't think it make sense to add that, but idea is cool. But, actually would be nice to hide some logs from Console, and store them in file logs instead which not important for the standard server owner, for example library not found, etc, but if server uses openmod for example, then that logs anyway will appear in console since it's already patched the logs by the OpenMod via harmony patches.

**Comment by MrRousek** [comment]
> Hi, these logs are coming from Unturned/Unity itself not rocket, they can be hidden with "harmony patches" (but that would require additional not super important support for that in future, and also it might break at some point) + will include new library in the project.
> 
> I don't think it make sense to add that, but idea is cool. But, actually would be nice to hide some logs from Console, and store them in file logs instead which not important for the standard server owner, for example library not found, etc, but if server uses openmod for example, then that logs anyway will appear in console since it's already patched the logs by the OpenMod via harmony patches.

hi, maybe there is an opportunity to write to the unturned developer and show him what he needs to fix?

**Comment by sunnamed434** [comment]
> > Hi, these logs are coming from Unturned/Unity itself not rocket, they can be hidden with "harmony patches" (but that would require additional not super important support for that in future, and also it might break at some point) + will include new library in the project.
> > 
> > I don't think it make sense to add that, but idea is cool. But, actually would be nice to hide some logs from Console, and store them in file logs instead which not important for the standard server owner, for example library not found, etc, but if server uses openmod for example, then that logs anyway will appear in console since it's already patched the logs by the OpenMod via harmony patches.
> 
> hi, maybe there is an opportunity to write to the unturned developer and show him what he needs to fix? 

Hi, I don't think it make sense to "fix", because it's not a problem at all, there are more important issues in Unturned that Nelson might fix rather than these logs, which are coming from Unity (my guess).

**Comment by sunnamed434** [comment]
And `Fallback handler could not load` is normal, it means Mono (Unity) loaded a library, it can be removed on Assembly code level, however, it doesn't make sense because if Unity got updated it might be break, so it will require additional support for that.

**Comment by sunnamed434** [comment]
Hi, last comments here explains why this change is not really needed, but maybe in future it might be added, but I think it still doesn't make sense. However I find your idea very interesting, I'm sure some folks will like it. 

For now, closing it.
