### ISSUE TITLE
Merge LDM: Fix V command exception

### ISSUE THREAD

**Issue by d3adwolf** [RocketModFix/RocketModFix#113]
[Legally-Distinct-Missile](https://github.com/SmartlyDressedGames/Legally-Distinct-Missile): https://github.com/RocketModFix/RocketModFix/commit/183c523d33e846699eefddbec502471cec1ffd95 and https://github.com/RocketModFix/RocketModFix/commit/a20b4ab53ca46db97ce2e71a1f9d5ff1022067d0

**Comment by sunnamed434** [comment]
Hi, isn't we already have this fix?

**Comment by d3adwolf** [comment]
@sunnamed434 

Well, I looked in the master branch, like, no.

```
List<VehicleAsset> assets = new List<VehicleAsset>();
                Assets.find(assets);
                foreach (VehicleAsset ia in assets)
```

**Comment by sunnamed434** [comment]
@d3adwolf

Gazzi made a fix for that, however it was made different, not the same as in LDM, see [here](https://github.com/RocketModFix/RocketModFix/commit/c22b594c2f6bd581debfaf9776a07ae5ca7021cc)

**Comment by sunnamed434** [comment]
We also have the [fix](https://github.com/RocketModFix/RocketModFix/blob/master/Rocket%2FRocket.Core%2FCommands%2FRocketCommandManager.cs#L165) for second commit you sent here.
