### ISSUE TITLE
Fix /god

### ISSUE THREAD

**Issue by sunnamed434** [RocketModFix/RocketModFix#13]
Even if the player in god player can die.

Rewrite whole god system seems a good idea to me

**Comment by vse3211** [comment]
See it: https://github.com/foreverfunface/UnturnedFullGodMode/releases/tag/v3.0
My little addon for default god mode and vanish
No damage, no infection, no bleeding, no broken, cant die

**Comment by sunnamed434** [comment]
Nice solution, good to integrate it in this fork

**Comment by ItsRodrigoAl** [comment]
> See it: https://github.com/foreverfunface/UnturnedFullGodMode/releases/tag/v3.0 My little addon for default god mode and vanish No damage, no infection, no bleeding, no broken, cant die

Would be cool if god mode algo gives you infinite stamina

**Comment by vse3211** [comment]
> > See it: https://github.com/foreverfunface/UnturnedFullGodMode/releases/tag/v3.0 My little addon for default god mode and vanish No damage, no infection, no bleeding, no broken, cant die
> 
> Would be cool if god mode algo gives you infinite stamina

Not problem
But not for vanish ... its cheating :)

Mb. other command:
`/stamina` `/st`

**Comment by vse3211** [comment]
Add inf stamina:
https://github.com/foreverfunface/UnturnedFullGodMode/commit/1fa4cde85a34982649c91215facc05ec08ed252f
Not without bugs, but it's work

**Comment by sunnamed434** [comment]
It makes sense to close issues about god and vanish (#12, #13) as not planned, remove from README info about that, and maybe make separate plugins or use existing solutions described in this issue by @vse3211
