### ISSUE TITLE
Add new AdminTools commands

### ISSUE THREAD

**Issue by mkspeed0** [RocketModFix/RocketModFix#18]
Add new AdminTools command. List of commands: /jump, /maxskills, /kickall, /clearinv, /checkowner, /exec, /execall

**Comment by Jdance-Media** [comment]
I disagree with this proposal. The current plugin that brings about these features (Shimmy's Admin Tools) already works fine. This is one of those things that would be nice-ish to have built into the core thing, but it really isn't needed.

**Comment by MrRousek** [comment]
The developer of this product does not want to change the kernel so much, only fix bugs. I don't quite agree with him, embedding a couple of free plugins into the core would be cool and would attract attention.

**Comment by MrRousek** [comment]
1

**Comment by sunnamed434** [comment]
Yeah, I agree, let's not make RocketModFix a tool of already-made plugins, basic commands like /pos are enough, if you need extra things really just better to use Shimmy's solution as Jdance mentioned

**Comment by mkspeed0** [comment]
Disagree
