### ISSUE TITLE
Add automatic saving

### ISSUE THREAD

**Issue by mkspeed0** [RocketModFix/RocketModFix#26]
Add automatic saving of plugin configuration

Before:
```
Plugin.Instance.Configuration.Instance.Test.Add(test);
Plugin.Instance.Configuration.Save();
```

After:
`Plugin.Instance.Configuration.Instance.Test.Add(test);`

I have demonstrated how the new save should look like, that is, without the extra code.

**Comment by sunnamed434** [comment]
I think its a bad idea because it can be a breaking change, also because even adding a default value `bool autoSave = false`, won't work, because the method signatures will be the same and it won't be compiled
