### ISSUE TITLE
UnturnedPlayer.DetailedCharacterName

### ISSUE THREAD

**Issue by sunnamed434** [RocketModFix/RocketModFix#29]
Can be useful for testing and debugging to see the DisplayName and SteamId, perhaps `DetailedCharacterName` does not fit very well, but happy to hear ideas from others

The same as in [openmod](https://github.com/openmod/openmod/blob/81024c3164efb9bf887a66e86b46d90682d6487b/framework/OpenMod.Core/Users/UserBase.cs#L29) (UserBase.FullActorName)

```cs
return $"{DisplayName} ({SteamId})";
```

**Comment by mkspeed0** [comment]
Yop, yep!
