### ISSUE TITLE
/compass should be phased out.

### ISSUE THREAD

**Issue by Jdance-Media** [RocketModFix/RocketModFix#34]
1. The new cartography volume makes it so any direction could be North, and there is an in-game compass.
2. The uses for this command are non-existent.
3. I have never seen a server purposefully enable this command for their players.

**Comment by sunnamed434** [comment]
Yeah, I also didn't see a server that uses the /compass command, but I guess somewhere there they exist, what if some server would like to sell (via donate by selling permission) command /compass ?

**Comment by Jdance-Media** [comment]
What would a donator use /compass for?

**Comment by sunnamed434** [comment]
> What would a donator use /compass for?

Idk, but I really don't see a reason to remove this command, I don't mind to remove this command, however, what if some servers use it, and due to it they won't install the RocketModFix

**Comment by Jdance-Media** [comment]
But that is exactly what I'm saying, what server actually has a use for /compass? I get something like /pos, but what direction you are facing? Alongside that, because you have the cartography volumes, it isn't even recommended to have something like that.

We might also have to consider that perhaps the game did not have a compass when the command was implemented. As the ID for the compass is 1508, indicating that it was added much after (also like to note that servers can enable the compass for all players by default).

**Comment by sunnamed434** [comment]
In this case, /compass command can be removed

**Comment by sunnamed434** [comment]
So, do we remove this command or not?
