### ISSUE TITLE
A lot of commands in Commands.config.xml cause server lags for any command

### ISSUE THREAD

**Issue by sunnamed434** [RocketModFix/RocketModFix#43]
Report from RocketMod user (not mine). I can provide a problematic plugin, just let me know.

For some reason when many commands are registered (250+) (commands of the plugin are registered via rocketmod automatically, not manually), then just execute some random like /11 (which doesn't even exist) this causes the server to lag for a few seconds, however, when a plugin with many commands is removed from the Plugin directory (as I understand unloaded) the problem disappears

**Comment by Jdance-Media** [comment]
Make it a dictionary.
