### ISSUE TITLE
Rocket.Unturned reference Rocket.Core and Rocket.API directly instead of nuget package

### ISSUE THREAD

**Issue by sunnamed434** [RocketModFix/RocketModFix#55]
https://github.com/RocketModFix/RocketModFix/blob/master/Rocket.Unturned/Rocket.Unturned.csproj#L11-L12

**Comment by Jdance-Media** [comment]
We would have to wait for the Core and/or API package to update before working on features in the Unturned project that rely on  changes to the Core and/or API.

**Comment by sunnamed434** [comment]
Yep, you're right

**Comment by Jdance-Media** [comment]
I oppose the PR, as it would interfere with multi-project edits.

**Comment by sunnamed434** [comment]
If you don't reference the .csproj inside of the .sln (solution) it doesn't allow you to reference the .csproj, however, maybe I was doing smth wrong
