### ISSUE TITLE
Changes related to Commands might be a breaking change

### ISSUE THREAD

**Issue by sunnamed434** [RocketModFix/RocketModFix#57]
(Report by @GazziFX) PR #48 can be a breaking change because [Commands](https://github.com/RocketModFix/RocketModFix/pull/48/commits/bfe7d6d3728341c257a8721da34e79fe94c94f29#diff-b4b720bf95f0a57d8976557b8e613225f725de288a9559e84a0140331649ca30L22) property can be a breaking change.

If he's right I'd suggest reverting changes from #48 PR

**Comment by GazziFX** [comment]
Maybe support both dictionary and list as fallback?

**Comment by sunnamed434** [comment]
Idk if it even makes sense to have a dictionary
