### ISSUE TITLE
Error in MulticastDelegate PlayerDisconnected

### ISSUE THREAD

**Issue by d3adwolf** [RocketModFix/RocketModFix#81]
I add an error from the logs for reporting, so far I have not seen that it somehow interferes or breaks the functionality, but since there is a bug, we need to fix it in the future. 

If you need additional information, I'm ready to provide it.

```csharp
2024-05-29 16:24:07.035	
  at Rocket.Core.Extensions.MulticastDelegateExtension.TryInvoke (System.MulticastDelegate theDelegate, System.Object[] args) [0x00013] in <2b8ee4b602174810b7294320f1aecbc4>:0 
2024-05-29 16:24:07.035	
  at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <2161c9885dd04ff291b79db9349c4b9b>:0 
2024-05-29 16:24:07.035	
  at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00008] in <2161c9885dd04ff291b79db9349c4b9b>:0 
2024-05-29 16:24:07.035	
  at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x000e7] in <2161c9885dd04ff291b79db9349c4b9b>:0 
2024-05-29 16:24:07.035	
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <2161c9885dd04ff291b79db9349c4b9b>:0 
2024-05-29 16:24:07.035	
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00083] in <2161c9885dd04ff291b79db9349c4b9b>:0 
2024-05-29 16:24:07.035	
   --- End of inner exception stack trace ---
2024-05-29 16:24:07.035	
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <2161c9885dd04ff291b79db9349c4b9b>:0 
2024-05-29 16:24:07.035	
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
2024-05-29 16:24:07.035	
  at FeexRanks.FeexRanksPlugin.OnPlayerDisconnected (Rocket.Unturned.Player.UnturnedPlayer player) [0x00049] in <9bd3ca080dab4fcbbb1be2b12821fe32>:0 
2024-05-29 16:24:07.035	
[5/29/2024 1:24:06 PM] [Error] Error in MulticastDelegate PlayerDisconnected: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
```

**Comment by MrRousek** [comment]
> I add an error from the logs for reporting, so far I have not seen that it somehow interferes or breaks the functionality, but since there is a bug, we need to fix it in the future.
> 
> If you need additional information, I'm ready to provide it.
> 
> ```cs
> 2024-05-29 16:24:07.035	
>   at Rocket.Core.Extensions.MulticastDelegateExtension.TryInvoke (System.MulticastDelegate theDelegate, System.Object[] args) [0x00013] in <2b8ee4b602174810b7294320f1aecbc4>:0 
> 2024-05-29 16:24:07.035	
>   at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <2161c9885dd04ff291b79db9349c4b9b>:0 
> 2024-05-29 16:24:07.035	
>   at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00008] in <2161c9885dd04ff291b79db9349c4b9b>:0 
> 2024-05-29 16:24:07.035	
>   at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x000e7] in <2161c9885dd04ff291b79db9349c4b9b>:0 
> 2024-05-29 16:24:07.035	
>   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <2161c9885dd04ff291b79db9349c4b9b>:0 
> 2024-05-29 16:24:07.035	
>   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00083] in <2161c9885dd04ff291b79db9349c4b9b>:0 
> 2024-05-29 16:24:07.035	
>    --- End of inner exception stack trace ---
> 2024-05-29 16:24:07.035	
>   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <2161c9885dd04ff291b79db9349c4b9b>:0 
> 2024-05-29 16:24:07.035	
>   at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
> 2024-05-29 16:24:07.035	
>   at FeexRanks.FeexRanksPlugin.OnPlayerDisconnected (Rocket.Unturned.Player.UnturnedPlayer player) [0x00049] in <9bd3ca080dab4fcbbb1be2b12821fe32>:0 
> 2024-05-29 16:24:07.035	
> [5/29/2024 1:24:06 PM] [Error] Error in MulticastDelegate PlayerDisconnected: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
> ```
I wonder if it is possible to get the dll of this plugin?

**Comment by MrRousek** [comment]
Or the event code for disconnecting from the server

**Comment by d3adwolf** [comment]
> > I add an error from the logs for reporting, so far I have not seen that it somehow interferes or breaks the functionality, but since there is a bug, we need to fix it in the future.
> > If you need additional information, I'm ready to provide it.
> > ```cs
> > 2024-05-29 16:24:07.035	
> >   at Rocket.Core.Extensions.MulticastDelegateExtension.TryInvoke (System.MulticastDelegate theDelegate, System.Object[] args) [0x00013] in <2b8ee4b602174810b7294320f1aecbc4>:0 
> > 2024-05-29 16:24:07.035	
> >   at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <2161c9885dd04ff291b79db9349c4b9b>:0 
> > 2024-05-29 16:24:07.035	
> >   at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00008] in <2161c9885dd04ff291b79db9349c4b9b>:0 
> > 2024-05-29 16:24:07.035	
> >   at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x000e7] in <2161c9885dd04ff291b79db9349c4b9b>:0 
> > 2024-05-29 16:24:07.035	
> >   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <2161c9885dd04ff291b79db9349c4b9b>:0 
> > 2024-05-29 16:24:07.035	
> >   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00083] in <2161c9885dd04ff291b79db9349c4b9b>:0 
> > 2024-05-29 16:24:07.035	
> >    --- End of inner exception stack trace ---
> > 2024-05-29 16:24:07.035	
> >   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <2161c9885dd04ff291b79db9349c4b9b>:0 
> > 2024-05-29 16:24:07.035	
> >   at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
> > 2024-05-29 16:24:07.035	
> >   at FeexRanks.FeexRanksPlugin.OnPlayerDisconnected (Rocket.Unturned.Player.UnturnedPlayer player) [0x00049] in <9bd3ca080dab4fcbbb1be2b12821fe32>:0 
> > 2024-05-29 16:24:07.035	
> > [5/29/2024 1:24:06 PM] [Error] Error in MulticastDelegate PlayerDisconnected: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
> > ```
> 
> I wonder if it is possible to get the dll of this plugin?

https://github.com/LeandroTheDev/feex_ranks_restored

**Comment by MrRousek** [comment]
> > > I add an error from the logs for reporting, so far I have not seen that it somehow interferes or breaks the functionality, but since there is a bug, we need to fix it in the future.
> > > If you need additional information, I'm ready to provide it.
> > > ```cs
> > > 2024-05-29 16:24:07.035	
> > >   at Rocket.Core.Extensions.MulticastDelegateExtension.TryInvoke (System.MulticastDelegate theDelegate, System.Object[] args) [0x00013] in <2b8ee4b602174810b7294320f1aecbc4>:0 
> > > 2024-05-29 16:24:07.035	
> > >   at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <2161c9885dd04ff291b79db9349c4b9b>:0 
> > > 2024-05-29 16:24:07.035	
> > >   at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00008] in <2161c9885dd04ff291b79db9349c4b9b>:0 
> > > 2024-05-29 16:24:07.035	
> > >   at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x000e7] in <2161c9885dd04ff291b79db9349c4b9b>:0 
> > > 2024-05-29 16:24:07.035	
> > >   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <2161c9885dd04ff291b79db9349c4b9b>:0 
> > > 2024-05-29 16:24:07.035	
> > >   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00083] in <2161c9885dd04ff291b79db9349c4b9b>:0 
> > > 2024-05-29 16:24:07.035	
> > >    --- End of inner exception stack trace ---
> > > 2024-05-29 16:24:07.035	
> > >   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <2161c9885dd04ff291b79db9349c4b9b>:0 
> > > 2024-05-29 16:24:07.035	
> > >   at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
> > > 2024-05-29 16:24:07.035	
> > >   at FeexRanks.FeexRanksPlugin.OnPlayerDisconnected (Rocket.Unturned.Player.UnturnedPlayer player) [0x00049] in <9bd3ca080dab4fcbbb1be2b12821fe32>:0 
> > > 2024-05-29 16:24:07.035	
> > > [5/29/2024 1:24:06 PM] [Error] Error in MulticastDelegate PlayerDisconnected: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
> > > ```
> > 
> > 
> > I wonder if it is possible to get the dll of this plugin?
> 
> https://github.com/LeandroTheDev/feex_ranks_restored

haha funny plugin, the first time I see that the plugin did not implement the unload

**Comment by MrRousek** [comment]
as far as I understand, this error is related to the plugin unloading from the server

**Comment by MrRousek** [comment]
oh, I'm sorry, I was thinking about something wrong, it's related to the player's exit from the server, at first glance it seems that this error is caused by the plugin and not as unrelated to the fork

**Comment by sunnamed434** [comment]
@MrRousek is right, the problem is on the plugin side, at least I checked the code and I already noticed a bunch of problems, I'll describe a few of them in the plugin issue [#1](https://github.com/LeandroTheDev/feex_ranks_restored/issues/1)

**Comment by sunnamed434** [comment]
If it is an issue on RocketModFix actually, then let us know, and we will reopen this
