### ISSUE TITLE
fix plugin's configuration .dat

### ISSUE THREAD

**Issue by mrgulka** [RocketModFix/RocketModFix#88]
in case of incorrect editing .dat plugin stops initializing. I suggest adding either an exception that will write exactly where the error occurred, or parse the old dat to the new one with the values from the config

//

в случае некорректного редактирования конфига .dat плагина  - перестает инициализироваться. Я предлагаю добавить либо исключение, которое будет показывать, где именно произошла ошибка, либо разбирать старый конфиг и парсить в новый конфиг (а где значения не подошли - дефолты ставить)

**Comment by sunnamed434** [comment]
I think it would be nice to unload the plugin (stop initializing as you described it) in case of problems with config

**Comment by mrgulka** [comment]
> I think it would be nice to unload the plugin (stop initializing as you described it) in case of problems with config

@sunnamed434 нужно добавить именно лог где произошла ошибка. сейчас же - в логах даже нет строки [loading] plugin_name

**Comment by Jdance-Media** [comment]
> > I think it would be nice to unload the plugin (stop initializing as you described it) in case of problems with config
> 
> 
> 
> @sunnamed434 нужно добавить именно лог где произошла ошибка. сейчас же - в логах даже нет строки [loading] plugin_name

Please, there are other contributors on this project that cannot understand Cyrillic language. Please consider adding an English translation.

**Comment by sunnamed434** [comment]
> > I think it would be nice to unload the plugin (stop initializing as you described it) in case of problems with config
> 
> @sunnamed434 нужно добавить именно лог где произошла ошибка. сейчас же - в логах даже нет строки [loading] plugin_name

Yeah, make sense

**Comment by mrgulka** [comment]
I couldn't reproduce the error, I tried to mess up the configuration, but the log say error in xml file

// 

я попытался испортить конфиг, но лог показал ошибку в xml файле

думаю что можно закрыть тикет...

**Comment by mrgulka** [comment]
I'm closing it, I couldn't reproduce the error, but the log appeared
