### ISSUE TITLE
We give up the meaningless plugin folder if it is not needed

### ISSUE THREAD

**Issue by MrRousek** [RocketModFix/RocketModFix#91]
Rocket mod necessarily creates a folder for the plugin, you need to fix it, because the plugin does not use this folder

**Comment by MrRousek** [comment]
let's say the plugin does not have a config and there is no localization. But a folder will still be created and there will be a localization file in it. 

by localization, I mean the file "\Servers\Default\Rocket\Plugins\[name]\[name].en.translation.xml "

**Comment by MrRousek** [comment]
in short, you just need to add if so that the module does not create a folder

**Comment by Jdance-Media** [comment]
These folders plus the extra XML rarely take up that much file space. They make no noticeable difference. I don't see why we need to prevent folder creation. Especially because some plugins modify/create files within them because they assume the folder will always exist (i.e. they don't check to see if the directory exists).

**Comment by sunnamed434** [comment]
> These folders plus the extra XML rarely take up that much file space. They make no noticeable difference. I don't see why we need to prevent folder creation. Especially because some plugins modify/create files within them because they assume the folder will always exist (i.e. they don't check to see if the directory exists).

It's a nice note, I do agree that many plugins might think that a plugin folder already exists as usual, to store DB files (for example LiteDB) or smth

**Comment by sunnamed434** [comment]
I don't see a reason for that change. Jdance's last comment here very nice explains the reason why it might be a bad change, and will cause more problems rather than solutions.

Closing it.
